# Generated by Django 5.1 on 2024-08-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
        ('puzzle', '0011_category_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Puzzle selected'), (5, 'Completed'), (6, "Time's up")], default=1)),
                ('puzzle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzle.puzzle')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival', to='multiplayer.presence')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplayer.presence')),
            ],
            options={
                'unique_together': {('starter', 'receiver')},
            },
        ),
    ]
