# Generated by Django 5.1 on 2024-08-23 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Ongoing'), (5, 'Completed'), (6, "Time's up")], default=1),
        ),
    ]
