# Generated by Django 5.0.6 on 2024-07-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuzzleCategories',
            new_name='PuzzleCategory',
        ),
    ]
