# Generated by Django 5.0.7 on 2024-08-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_development_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='on_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
