# Generated by Django 5.0.7 on 2024-08-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_attempt_on_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzletest',
            old_name='problem',
            new_name='puzzle',
        ),
    ]
