# Generated by Django 5.1 on 2024-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_rename_problem_puzzletest_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='task_id',
            field=models.CharField(default='INVALID_ID', max_length=255),
            preserve_default=False,
        ),
    ]
