# Generated by Django 5.1 on 2024-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_attempt_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
