# Generated by Django 5.1 on 2024-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_development_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='build_error',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
