# Generated by Django 5.1 on 2024-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_attempt_build_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='build_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
