# Generated by Django 5.1 on 2024-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0010_alter_attempt_build_error_alter_attempt_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
