# Generated by Django 5.1 on 2024-08-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_challenge'),
        ('puzzle', '0011_category_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='challenge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplayer.challenge'),
        ),
    ]
