# Generated by Django 5.1 on 2024-09-01 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0012_development_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'description', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='puzzle_puzz_search__288015_gin'),
        ),
    ]
