# Generated by Django 5.1 on 2024-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0013_puzzle_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='visibility',
            field=models.CharField(choices=[('P', 'Public'), ('H', 'Hidden'), ('R', 'Private')], default='P', max_length=1),
        ),
    ]
